import {Hand} from '../shared/models/hand/Hand';
import {HandRange} from '../shared/models/HandRange';
import {Folder} from '../shared/models/Folder';

export const Defaults = new Folder('defaults',
  [
    new Folder(
      '6-max',
      [new HandRange(
        'UTG_6_MAX_OPEN_RAISE',
        'default',
        new Set([
          Hand.pAA,
          Hand.sAK,
          Hand.sAQ,
          Hand.sAJ,
          Hand.sAT,
          Hand.sA9,
          Hand.sA8,
          Hand.oAK,
          Hand.pKK,
          Hand.sKQ,
          Hand.sKJ,
          Hand.sKT,
          Hand.oAQ,
          Hand.oKQ,
          Hand.pQQ,
          Hand.p55,
          Hand.sQJ,
          Hand.sQT,
          Hand.oAJ,
          Hand.oKJ,
          Hand.pJJ,
          Hand.sJT,
          Hand.oAT,
          Hand.pTT,
          Hand.p99,
          Hand.p88,
          Hand.p77,
          Hand.p66,
        ])
      ),
        new HandRange(
          'Plus1_6MAX_OPEN_RAISE',
          'default',
          new Set(
            [Hand.pAA,
              Hand.sAK,
              Hand.sAQ,
              Hand.sAJ,
              Hand.sAT,
              Hand.sA9,
              Hand.sA8,
              Hand.oAK,
              Hand.pKK,
              Hand.sKQ,
              Hand.sKJ,
              Hand.sKT,
              Hand.oAQ,
              Hand.oKQ,
              Hand.pQQ,
              Hand.p55,
              Hand.sQJ,
              Hand.sQT,
              Hand.oAJ,
              Hand.oKJ,
              Hand.pJJ,
              Hand.sJT,
              Hand.oAT,
              Hand.pTT,
              Hand.p99,
              Hand.p88,
              Hand.p77,
              Hand.p66
            ])
        )]
    ),
    new Folder(
      '9-max',
      [new HandRange(
        'UTG_9_MAX_OPEN_RAISE',
        'default',
        new Set([
          Hand.pAA,
          Hand.sAK,
          Hand.sAQ,
          Hand.sAJ,
          Hand.sAT,
          Hand.sA9,
          Hand.sA8,
          Hand.oAK,
          Hand.pKK,
          Hand.sKQ,
          Hand.sKJ,
          Hand.sKT,
          Hand.oAQ,
          Hand.oKQ,
          Hand.pQQ,
          Hand.p55,
          Hand.sQJ,
          Hand.sQT,
          Hand.oAJ,
          Hand.oKJ,
          Hand.pJJ,
          Hand.sJT,
          Hand.oAT,
          Hand.pTT,
          Hand.p99,
          Hand.p88,
          Hand.p77,
          Hand.p66,
        ])
      ),
        new HandRange(
          'Plus1_9MAX_OPEN_RAISE',
          'default',
          new Set(
            [Hand.pAA,
              Hand.sAK,
              Hand.sAQ,
              Hand.sAJ,
              Hand.sAT,
              Hand.sA9,
              Hand.sA8,
              Hand.oAK,
              Hand.pKK,
              Hand.sKQ,
              Hand.sKJ,
              Hand.sKT,
              Hand.oAQ,
              Hand.oKQ,
              Hand.pQQ,
              Hand.p55,
              Hand.sQJ,
              Hand.sQT,
              Hand.oAJ,
              Hand.oKJ,
              Hand.pJJ,
              Hand.sJT,
              Hand.oAT,
              Hand.pTT,
              Hand.p99,
              Hand.p88,
              Hand.p77,
              Hand.p66
            ])
        )]
    )
  ]
);

